name: planter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: ^0.5.2
  cupertino_icons: ^1.0.5
  flutter_virtual_piano: ^0.0.8
  file_picker: ^8.0.6
  csv: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/planter_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
